package in.sahayak.documents;
import android.app.*;import android.os.*;import android.content.*;import android.webkit.*;import android.print.*;import android.widget.*;import java.io.*;

/** Local HTML only. No scripts, external requests, local filesystem or content access. */
public class HtmlActivity extends Activity {
 WebView web;Button print;TextView note;
 @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,32,24,24);root.setBackgroundColor(0xfffff8eb);setContentView(root);Button back=new Button(this);back.setText("← Back / वापस");back.setOnClickListener(v->finish());root.addView(back);note=new TextView(this);note.setTextSize(18);note.setText("Local HTML → PDF\nChoose an HTML file, review it, then select Save as PDF in Android's print screen. Scripts and remote content are blocked.");root.addView(note);Button choose=new Button(this);choose.setText("Choose HTML file");choose.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("text/html");startActivityForResult(i,1);});root.addView(choose);
  web=new WebView(this);web.getSettings().setJavaScriptEnabled(false);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setBlockNetworkLoads(true);web.getSettings().setDomStorageEnabled(false);web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest r){return true;}@Override public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest request){return new WebResourceResponse("text/plain","UTF-8",new ByteArrayInputStream(new byte[0]));}@Override public void onPageFinished(WebView view,String url){print.setEnabled(true);}});root.addView(web,new LinearLayout.LayoutParams(-1,0,1));print=new Button(this);print.setText("Print preview / PDF सहेजें");print.setEnabled(false);print.setOnClickListener(v->{try{((PrintManager)getSystemService(PRINT_SERVICE)).print("maapdf HTML",web.createPrintDocumentAdapter("maapdf-html"),new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).build());}catch(Exception e){note.setText("Android print service unavailable: "+e.getMessage());}});root.addView(print);
 }
 @Override public void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request!=1||result!=RESULT_OK||data==null||data.getData()==null)return;try(InputStream in=getContentResolver().openInputStream(data.getData());ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(out.size()+n>2*1024*1024)throw new IOException("Use HTML files under 2 MB");out.write(b,0,n);}print.setEnabled(false);web.loadDataWithBaseURL(null,out.toString("UTF-8"),"text/html","UTF-8",null);}catch(Exception e){note.setText(e.getMessage());}}
 @Override public void onDestroy(){if(web!=null){web.stopLoading();web.destroy();}super.onDestroy();}
}
