package in.sahayak.documents;

import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.database.Cursor;import android.provider.OpenableColumns;import android.graphics.*;import android.graphics.pdf.*;import android.speech.*;import android.speech.tts.TextToSpeech;import android.view.*;import android.widget.*;import android.text.InputType;
import java.io.*;import java.util.*;import java.util.zip.*;import java.net.*;import org.json.*;import org.xmlpull.v1.*;

public class MainActivity extends Activity {
 LinearLayout root,body; TextView status; EditText editor,command; TextToSpeech tts; boolean ttsReady=false,editable=false,dirty=false; String name="New document.txt",original=""; byte[] pending; PdfRenderer pdf; ParcelFileDescriptor descriptor; int page=0; Bitmap shown; File currentPdf;
 final int OPEN=1,SAVE=2,VOICE=3,PHOTO=4,CAMERA=5;
 void message(String s){new AlertDialog.Builder(this).setMessage(s).setPositiveButton("OK / ठीक",null).show();}
 TextView label(String s,int size){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(Color.rgb(24,44,55));v.setPadding(8,12,8,12);return v;}
 Button button(String s,Runnable r){Button b=new Button(this);b.setText(s);b.setTextSize(19);b.setMinHeight(64);b.setAllCaps(false);b.setTextColor(Color.rgb(38,72,53));b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(232,237,216)));b.setOnClickListener(v->r.run());return b;}
 void row(LinearLayout parent,Button...buttons){LinearLayout r=new LinearLayout(this);for(Button b:buttons)r.addView(b,new LinearLayout.LayoutParams(0,-2,1));parent.addView(r);}
 @Override public void onCreate(Bundle state){super.onCreate(state);com.tom_roush.pdfbox.android.PDFBoxResourceLoader.init(getApplicationContext());getWindow().setStatusBarColor(Color.rgb(255,248,235));root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(16,24,16,16);root.setBackgroundColor(Color.rgb(255,248,235));root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(16,i.getSystemWindowInsetTop()+12,16,i.getSystemWindowInsetBottom()+12);return i;});setContentView(root);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
 root.addView(new MaaHeader(this));
 row(root,button("Open / खोलें",()->guard(()->pick("*/*",OPEN))),button("PDF tools / टूल",()->startActivity(new Intent(this,ToolsActivity.class))));
 status=label("Ready • तैयार",16);root.addView(status);ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
 command=new EditText(this);command.setTextSize(18);command.setHint("Try: replace Suresh with Ramesh");command.setSingleLine(true);root.addView(command);
 row(root,button("Speak / बोलें",()->{try{Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"hi-IN");i.putExtra(RecognizerIntent.EXTRA_PROMPT,"Hindi, English or Hinglish");startActivityForResult(i,VOICE);}catch(Exception e){message("Voice recognition unavailable. Type your command below.");}}),button("Do / करें",()->execute(command.getText().toString())));
 row(root,button("Read / सुनें",()->read()),button("Save copy",()->save()));root.addView(button("More / और विकल्प",()->more()));
 tts=new TextToSpeech(this,s->{ttsReady=s==TextToSpeech.SUCCESS;});textDocument("New document.txt",getIntent().getStringExtra("draft")==null?"":getIntent().getStringExtra("draft"),true);
 }
 void more(){new AlertDialog.Builder(this).setTitle("More / और विकल्प").setItems(new String[]{"New text document","Photo to PDF","Quick camera capture","Help & backend","Text preview → PDF"},(dialog,which)->{if(which==0)guard(()->textDocument("New document.txt","",true));if(which==1)guard(()->pick("image/*",PHOTO));if(which==2)guard(()->{try{startActivityForResult(new Intent("android.media.action.IMAGE_CAPTURE"),CAMERA);}catch(Exception e){message("Camera unavailable. Use Photo import.");}});if(which==3)help();if(which==4)exportTextPdf();}).show();}
 void guard(Runnable action){if(editable&&editor!=null&&!editor.getText().toString().equals(original))new AlertDialog.Builder(this).setMessage("Discard unsaved changes? / बदलाव हटाएँ?").setNegativeButton("Cancel",null).setPositiveButton("Discard",(d,w)->action.run()).show();else action.run();}
 void pick(String type,int request){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(type);startActivityForResult(i,request);}
 void closePdf(){if(pdf!=null){pdf.close();pdf=null;}try{if(descriptor!=null)descriptor.close();}catch(Exception ignored){} descriptor=null;}
 void textDocument(String title,String value,boolean edit){closePdf();name=title;original=value;editable=edit;body.removeAllViews();editor=new EditText(this);editor.setTextSize(21);editor.setHint("Type here / यहाँ लिखें");editor.setGravity(Gravity.TOP);editor.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);editor.setMinLines(8);editor.setText(value);editor.setFocusable(edit);editor.setCursorVisible(edit);body.addView(editor);status.setText(title+(edit?" • Editable copy":" • Text preview only"));if(!edit)body.addView(button("Edit as TXT copy",()->new AlertDialog.Builder(this).setMessage("Create a plain-text copy? Office layout, images and formulas will not be retained.").setNegativeButton("Cancel",null).setPositiveButton("Create copy",(d,w)->textDocument(title+".txt",value,true)).show()));}
 byte[] bytes(InputStream in,int limit)throws Exception{try(InputStream stream=in;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=stream.read(b))!=-1){if(out.size()+n>limit)throw new IOException("File too large for V1 (20 MB file / 4 MB extracted text limit).");out.write(b,0,n);}return out.toByteArray();}}
 String filename(Uri uri){try(Cursor c=getContentResolver().query(uri,null,null,null,null)){if(c!=null&&c.moveToFirst()){int p=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(p>=0)return c.getString(p);}}return "document";}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK)return;try{
 if(request==VOICE){ArrayList<String> words=data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(words!=null&&!words.isEmpty()){command.setText(words.get(0));execute(words.get(0));}return;}
 if(request==CAMERA){Bitmap b=(Bitmap)data.getExtras().get("data");if(b!=null){photoPdf(b);message("Quick camera preview captured. For a sharper scan, take a photo in your camera app and use Photo import.");}return;}
 if(data==null||data.getData()==null)return;Uri uri=data.getData();
 if(request==SAVE){try(OutputStream out=getContentResolver().openOutputStream(uri,"w")){out.write(pending);}pending=null;if(editable)original=editor.getText().toString();message("Copy saved / कॉपी सहेजी गई");return;}
 byte[] content=bytes(getContentResolver().openInputStream(uri),20*1024*1024);
 if(request==PHOTO){BitmapFactory.Options opts=new BitmapFactory.Options();opts.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(content,0,content.length,opts);opts.inSampleSize=Math.max(1,Math.max(opts.outWidth,opts.outHeight)/1800);opts.inJustDecodeBounds=false;Bitmap b=BitmapFactory.decodeByteArray(content,0,content.length,opts);if(b==null)throw new IOException("Unsupported image");photoPdf(b);return;}
 String title=filename(uri),ext=title.toLowerCase(Locale.ROOT);if(ext.endsWith(".pdf")){File f=new File(getCacheDir(),"opened.pdf");try(FileOutputStream out=new FileOutputStream(f)){out.write(content);}openPdf(f,title);}
 else if(ext.endsWith(".docx")||ext.endsWith(".xlsx"))textDocument(title,office(content,ext.endsWith(".xlsx")),false);
 else if(ext.endsWith(".txt")||ext.endsWith(".csv")){textDocument(title,new String(content,java.nio.charset.StandardCharsets.UTF_8),true);}
 else message("Choose PDF, DOCX, XLSX, CSV or UTF-8 TXT. Use Photo for images.");
 }catch(Exception e){message("Could not complete: "+e.getMessage());}}
 void openPdf(File file,String title)throws Exception{closePdf();descriptor=ParcelFileDescriptor.open(file,ParcelFileDescriptor.MODE_READ_ONLY);pdf=new PdfRenderer(descriptor);currentPdf=file;name=title;editable=false;editor=null;page=0;render();}
 void render(){if(pdf==null)return;body.removeAllViews();row(body,button("← Previous",()->{if(page>0){page--;render();}}),button("Next →",()->{if(page+1<pdf.getPageCount()){page++;render();}}));try(PdfRenderer.Page p=pdf.openPage(page)){int width=1000;int height=Math.min(3000,Math.max(1,(int)((long)width*p.getHeight()/p.getWidth())));Bitmap b=Bitmap.createBitmap(width,height,Bitmap.Config.ARGB_8888);b.eraseColor(Color.WHITE);p.render(b,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);ImageView image=new ImageView(this);image.setAdjustViewBounds(true);image.setImageBitmap(b);image.setContentDescription("PDF page "+(page+1));body.addView(image);shown=b;}status.setText(name+" • Page "+(page+1)+" / "+pdf.getPageCount());}
 void photoPdf(Bitmap b)throws Exception{File file=new File(getCacheDir(),"photo.pdf");PdfDocument doc=new PdfDocument();try{PdfDocument.Page p=doc.startPage(new PdfDocument.PageInfo.Builder(b.getWidth(),b.getHeight(),1).create());p.getCanvas().drawBitmap(b,0,0,null);doc.finishPage(p);try(FileOutputStream out=new FileOutputStream(file)){doc.writeTo(out);}}finally{doc.close();}openPdf(file,"Scan.pdf");}
 void save(){if(pdf==null&&!editable){message("Office preview: choose Edit as TXT copy first.");return;}new AlertDialog.Builder(this).setTitle("Save a new copy?").setMessage("Your original file stays unchanged. / मूल फाइल नहीं बदलेगी।").setNegativeButton("Cancel",null).setPositiveButton("Confirm / पुष्टि",(d,w)->{try{if(pdf!=null){File f=currentPdf;pending=bytes(new FileInputStream(f),20*1024*1024);}else pending=editor.getText().toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(pdf!=null?"application/pdf":name.endsWith(".csv")?"text/csv":"text/plain");i.putExtra(Intent.EXTRA_TITLE,"Copy-"+name);startActivityForResult(i,SAVE);}catch(Exception e){message(e.getMessage());}}).show();}
 void read(){if(editor!=null){speakText(editor.getText().toString());return;}if(currentPdf!=null){File source=currentPdf;new Thread(()->{try{String text=PdfEngine.text(source,"");runOnUiThread(()->{if(text.trim().isEmpty())message("No selectable text. This scan needs OCR.");else speakText(text);});}catch(Exception e){runOnUiThread(()->message("Could not read this PDF: "+e.getMessage()));}}).start();}}
 void speakText(String text){if(!ttsReady){message("Speech engine is not ready. Check Android text-to-speech settings.");return;}tts.setLanguage(text.matches("(?s).*[\\u0900-\\u097F].*")?new Locale("hi","IN"):Locale.ENGLISH);tts.stop();int max=TextToSpeech.getMaxSpeechInputLength()-1;for(int i=0;i<text.length();i+=max)tts.speak(text.substring(i,Math.min(text.length(),i+max)),TextToSpeech.QUEUE_ADD,null,"read"+i);}
 void exportTextPdf(){if(editor==null){message("Open a text or Office text preview first.");return;}String text=editor.getText().toString();new AlertDialog.Builder(this).setMessage("Create a PDF of this text? Office images and original layout are not retained.").setNegativeButton("Cancel",null).setPositiveButton("Create preview",(dialog,which)->{try{android.text.TextPaint paint=new android.text.TextPaint(Paint.ANTI_ALIAS_FLAG);paint.setColor(Color.BLACK);paint.setTextSize(14);android.text.StaticLayout layout=android.text.StaticLayout.Builder.obtain(text,0,text.length(),paint,499).setIncludePad(false).build();int count=Math.max(1,(layout.getHeight()+745)/746);if(count>200){message("Text is too long. Maximum 200 pages.");return;}File file=new File(getCacheDir(),"text-"+UUID.randomUUID()+".pdf");PdfDocument doc=new PdfDocument();try{for(int i=0;i<count;i++){PdfDocument.Page p=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,i+1).create());Canvas canvas=p.getCanvas();canvas.save();canvas.clipRect(48,48,547,794);canvas.translate(48,48-i*746);layout.draw(canvas);canvas.restore();doc.finishPage(p);}try(FileOutputStream out=new FileOutputStream(file)){doc.writeTo(out);}}finally{doc.close();}openPdf(file,"Text.pdf");}catch(Exception e){message(e.getMessage());}}).show();}
 void execute(String input){String[] intent=IntentParser.parse(input);if(intent[0].equals("unknown")){String endpoint=getPreferences(0).getString("endpoint","");if(endpoint.isEmpty()){message("Try: next page, page 2, padho, save, replace Suresh with Ramesh, or Suresh ki jagah Ramesh likho.");return;}new AlertDialog.Builder(this).setMessage("Send this command to your configured backend? Only command text is sent, not your file.\n\n"+input).setNegativeButton("Cancel",null).setPositiveButton("Send",(d,w)->remote(endpoint,input)).show();}else apply(intent);}
 void apply(String[] a){switch(a[0]){case "open":guard(()->pick("*/*",OPEN));break;case "read":read();break;case "save":save();break;case "next":if(pdf!=null&&page+1<pdf.getPageCount()){page++;render();}break;case "previous":if(pdf!=null&&page>0){page--;render();}break;case "page":try{int n=Integer.parseInt(a[1]);if(pdf!=null&&n>=1&&n<=pdf.getPageCount()){page=n-1;render();}else message("Page unavailable.");}catch(Exception e){message("Invalid page.");}break;case "replace":if(!editable||editor==null){message("Open editable text first. Office files can be converted to a TXT copy.");break;}String before=editor.getText().toString();if(a.length<3||a[1].isEmpty()||!before.contains(a[1])){message("Text not found.");break;}String after=before.replace(a[1],a[2]);int count=(before.length()-before.replace(a[1],"").length())/a[1].length();new AlertDialog.Builder(this).setTitle("Confirm replacement").setMessage(a[1]+" → "+a[2]+"\n"+count+" occurrence(s). Original file unchanged until you save a copy.").setNegativeButton("Cancel",null).setPositiveButton("Confirm",(d,w)->editor.setText(after)).show();break;default:message("Command not understood. Please use the buttons.");}}
 void remote(String endpoint,String text){new Thread(()->{try{URL url=new URL(endpoint+"/intent");HttpURLConnection c=(HttpURLConnection)url.openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");byte[] payload=new JSONObject().put("text",text).toString().getBytes("UTF-8");try(OutputStream out=c.getOutputStream()){out.write(payload);}JSONObject j=new JSONObject(new String(bytes(c.getInputStream(),8192),"UTF-8"));String action=j.getString("action");String[] a=action.equals("replace")?new String[]{action,j.getString("from"),j.getString("to")}:action.equals("page")?new String[]{action,j.getString("page")}:new String[]{action};runOnUiThread(()->apply(a));c.disconnect();}catch(Exception e){runOnUiThread(()->message("Backend unavailable. Local buttons and common commands still work."));}}).start();}
 void help(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(24,12,24,12);box.addView(label("PDF tools: arrange, convert, annotate, protect and compare. DOCX/XLSX: text preview; convert text to PDF or TXT. Read & understand includes English/Hindi OCR, key-sentence summaries and text translation. Full Office layout editing is not included. Google ML Kit processes content locally, may download models and send usage/performance metrics. Tap Maa to pause or resume her animation. Voice availability depends on your phone and may use its speech provider.\nOptional Lightning HTTPS backend (no file uploads):",16));EditText url=new EditText(this);url.setSingleLine();url.setHint("https://your-studio-endpoint");url.setText(getPreferences(0).getString("endpoint",""));box.addView(url);new AlertDialog.Builder(this).setTitle("Help / मदद").setView(box).setNegativeButton("Close",null).setNeutralButton("Stop reading",(d,w)->tts.stop()).setPositiveButton("Save backend",(d,w)->{String s=url.getText().toString().trim().replaceAll("/+$","");try{if(!s.isEmpty()){URL u=new URL(s);if(!u.getProtocol().equals("https")||u.getUserInfo()!=null||u.getQuery()!=null)throw new Exception();}getPreferences(0).edit().putString("endpoint",s).apply();}catch(Exception e){message("Enter an HTTPS address without credentials or query parameters.");}}).show();}
 String office(byte[] bytes,boolean sheet)throws Exception{Map<String,byte[]> parts=new TreeMap<>();int total=0;try(ZipInputStream z=new ZipInputStream(new ByteArrayInputStream(bytes))){ZipEntry e;int entries=0;while((e=z.getNextEntry())!=null){if(++entries>2000)throw new IOException("Too many archive entries");String n=e.getName();if(n.equals("word/document.xml")||n.equals("xl/sharedStrings.xml")||n.matches("xl/worksheets/sheet[0-9]+\\.xml")){ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[4096];int k;while((k=z.read(b))!=-1){total+=k;if(total>4*1024*1024)throw new IOException("Office content too large");out.write(b,0,k);}parts.put(n,out.toByteArray());}}}StringBuilder result=new StringBuilder();List<String> shared=new ArrayList<>();if(parts.containsKey("xl/sharedStrings.xml")){XmlPullParser p=xml(parts.get("xl/sharedStrings.xml"));StringBuilder item=new StringBuilder();while(p.next()!=XmlPullParser.END_DOCUMENT){if(p.getEventType()==2&&p.getName().equals("si"))item=new StringBuilder();if(p.getEventType()==2&&p.getName().equals("t"))item.append(p.nextText());if(p.getEventType()==3&&p.getName().equals("si"))shared.add(item.toString());}}
 for(Map.Entry<String,byte[]> entry:parts.entrySet()){if(entry.getKey().contains("sharedStrings"))continue;if(sheet)result.append("\n").append(entry.getKey()).append(" (cached values)\n");XmlPullParser p=xml(entry.getValue());String type="",cell="";while(p.next()!=XmlPullParser.END_DOCUMENT){if(p.getEventType()==2){String n=p.getName();if(n.equals("c")){type=p.getAttributeValue(null,"t");cell=p.getAttributeValue(null,"r");result.append(cell).append(": ");}if(n.equals("t"))result.append(p.nextText());if(sheet&&n.equals("v")){String v=p.nextText();if("s".equals(type)){int i=Integer.parseInt(v);v=i>=0&&i<shared.size()?shared.get(i):"";}result.append(v);}}if(p.getEventType()==3){String n=p.getName();if(n.equals("p")||n.equals("row"))result.append('\n');if(n.equals("c"))result.append("   ");}}}return result.toString();}
 XmlPullParser xml(byte[] b)throws Exception{XmlPullParser p=android.util.Xml.newPullParser();p.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES,true);p.setInput(new ByteArrayInputStream(b),"UTF-8");return p;}
 @Override public void onBackPressed(){guard(()->finish());}
 @Override protected void onDestroy(){closePdf();if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
}
