package in.sahayak.documents;

import java.io.*;import java.util.*;import java.util.zip.*;
import android.graphics.*;
import com.tom_roush.pdfbox.pdmodel.*;
import com.tom_roush.pdfbox.pdmodel.common.PDRectangle;
import com.tom_roush.pdfbox.pdmodel.graphics.image.JPEGFactory;
import com.tom_roush.pdfbox.rendering.PDFRenderer;

public final class PortableExports {
 static String xml(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replaceAll("[\\x00-\\x08\\x0B\\x0C\\x0E-\\x1F]","");}
 static void entry(ZipOutputStream z,String name,String value)throws Exception{z.putNextEntry(new ZipEntry(name));z.write(value.getBytes("UTF-8"));z.closeEntry();}
 static final String CT="http://schemas.openxmlformats.org/package/2006/content-types";
 static final String REL="http://schemas.openxmlformats.org/package/2006/relationships";
 static final String OFFICE="http://schemas.openxmlformats.org/officeDocument/2006/relationships/";
 static String relation(String id,String type,String target){return "<Relationship Id=\""+id+"\" Type=\""+OFFICE+type+"\" Target=\""+target+"\"/>";}
 public static void word(String text,File out)throws Exception{try(ZipOutputStream z=new ZipOutputStream(new FileOutputStream(out))){entry(z,"[Content_Types].xml","<Types xmlns=\""+CT+"\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/word/document.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml\"/></Types>");entry(z,"_rels/.rels","<Relationships xmlns=\""+REL+"\">"+relation("rId1","officeDocument","word/document.xml")+"</Relationships>");StringBuilder body=new StringBuilder("<w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"><w:body>");for(String line:text.split("\n",-1))body.append("<w:p><w:r><w:t xml:space=\"preserve\">").append(xml(line)).append("</w:t></w:r></w:p>");body.append("<w:sectPr/></w:body></w:document>");entry(z,"word/document.xml",body.toString());}}
 public static void excel(String text,File out)throws Exception{try(ZipOutputStream z=new ZipOutputStream(new FileOutputStream(out))){entry(z,"[Content_Types].xml","<Types xmlns=\""+CT+"\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");entry(z,"_rels/.rels","<Relationships xmlns=\""+REL+"\">"+relation("rId1","officeDocument","xl/workbook.xml")+"</Relationships>");entry(z,"xl/workbook.xml","<workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Extracted text\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");entry(z,"xl/_rels/workbook.xml.rels","<Relationships xmlns=\""+REL+"\">"+relation("rId1","worksheet","worksheets/sheet1.xml")+"</Relationships>");StringBuilder body=new StringBuilder("<worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetData>");int i=0;for(String line:text.split("\n",-1)){if(line.length()>32767)throw new Exception("A line is too long for a spreadsheet cell");body.append("<row r=\"").append(++i).append("\"><c r=\"A").append(i).append("\" t=\"inlineStr\"><is><t xml:space=\"preserve\">").append(xml(line)).append("</t></is></c></row>");}body.append("</sheetData></worksheet>");entry(z,"xl/worksheets/sheet1.xml",body.toString());}}
 public static String compare(String a,String b){if(a.equals(b))return "Extracted text is identical. This does not prove visual or document authenticity equivalence.";String[] left=a.split("\n"),right=b.split("\n");StringBuilder s=new StringBuilder("Text comparison — lines at the same position\nA blank or inserted line can shift later comparisons. Images are not compared.\n\n");for(int i=0;i<Math.max(left.length,right.length);i++){String x=i<left.length?left[i]:"",y=i<right.length?right[i]:"";if(!x.equals(y))s.append("Line ").append(i+1).append("\nA: ").append(x).append("\nB: ").append(y).append("\n\n");}return s.toString();}
 public static void redact(File input,String password,String arg,File output)throws Exception{
  String[] parts=arg.split(",");if(parts.length!=5)throw new Exception("Use page,x,y,width,height, for example 1,10,10,60,15");int page=Integer.parseInt(parts[0].trim());float x=Float.parseFloat(parts[1].trim()),y=Float.parseFloat(parts[2].trim()),w=Float.parseFloat(parts[3].trim()),h=Float.parseFloat(parts[4].trim());
  if(!Float.isFinite(x)||!Float.isFinite(y)||!Float.isFinite(w)||!Float.isFinite(h)||x<0||y<0||w<=0||h<=0||x+w>100||y+h>100)throw new Exception("Rectangle must fit within 0–100 percent");
  try(PDDocument d=PdfEngine.load(input,password);PDDocument out=new PDDocument()){if(page<1||page>d.getNumberOfPages())throw new Exception("Page not found");PDFRenderer renderer=new PDFRenderer(d);for(int i=0;i<d.getNumberOfPages();i++){Bitmap b=renderer.renderImage(i,Math.min(1.5f,1800f/Math.max(d.getPage(i).getMediaBox().getWidth(),d.getPage(i).getMediaBox().getHeight())));if(i==page-1){Canvas c=new Canvas(b);Paint paint=new Paint();paint.setColor(Color.BLACK);c.drawRect(x*b.getWidth()/100,y*b.getHeight()/100,(x+w)*b.getWidth()/100,(y+h)*b.getHeight()/100,paint);}PDPage p=new PDPage(new PDRectangle(b.getWidth(),b.getHeight()));out.addPage(p);try(PDPageContentStream c=new PDPageContentStream(out,p)){c.drawImage(JPEGFactory.createFromImage(out,b,.9f),0,0,b.getWidth(),b.getHeight());}b.recycle();}out.save(output);}
 }
 public static void slides(File input,String password,File output)throws Exception{
  try(PDDocument d=PdfEngine.load(input,password);ZipOutputStream z=new ZipOutputStream(new FileOutputStream(output))){int n=d.getNumberOfPages();StringBuilder types=new StringBuilder("<Types xmlns=\""+CT+"\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Default Extension=\"jpg\" ContentType=\"image/jpeg\"/><Override PartName=\"/ppt/presentation.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml\"/>");StringBuilder list=new StringBuilder(),rels=new StringBuilder("<Relationships xmlns=\""+REL+"\">");PDFRenderer renderer=new PDFRenderer(d);
   for(int i=1;i<=n;i++){types.append("<Override PartName=\"/ppt/slides/slide").append(i).append(".xml\" ContentType=\"application/vnd.openxmlformats-officedocument.presentationml.slide+xml\"/>");list.append("<p:sldId id=\"").append(255+i).append("\" r:id=\"rId").append(i).append("\"/>");rels.append(relation("rId"+i,"slide","slides/slide"+i+".xml"));Bitmap b=renderer.renderImage(i-1,Math.min(1.5f,1800f/Math.max(d.getPage(i-1).getMediaBox().getWidth(),d.getPage(i-1).getMediaBox().getHeight())));long height=6858000,width=9144000;double scale=Math.min(width/(double)b.getWidth(),height/(double)b.getHeight());long iw=(long)(b.getWidth()*scale),ih=(long)(b.getHeight()*scale);
    entry(z,"ppt/slides/slide"+i+".xml","<p:sld xmlns:p=\"http://schemas.openxmlformats.org/presentationml/2006/main\" xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id=\"1\" name=\"\"/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/><p:pic><p:nvPicPr><p:cNvPr id=\"2\" name=\"Page "+i+"\"/><p:cNvPicPr/><p:nvPr/></p:nvPicPr><p:blipFill><a:blip r:embed=\"rId1\"/><a:stretch><a:fillRect/></a:stretch></p:blipFill><p:spPr><a:xfrm><a:off x=\""+(width-iw)/2+"\" y=\""+(height-ih)/2+"\"/><a:ext cx=\""+iw+"\" cy=\""+ih+"\"/></a:xfrm><a:prstGeom prst=\"rect\"><a:avLst/></a:prstGeom></p:spPr></p:pic></p:spTree></p:cSld></p:sld>");entry(z,"ppt/slides/_rels/slide"+i+".xml.rels","<Relationships xmlns=\""+REL+"\">"+relation("rId1","image","../media/page"+i+".jpg")+"</Relationships>");z.putNextEntry(new ZipEntry("ppt/media/page"+i+".jpg"));b.compress(Bitmap.CompressFormat.JPEG,88,z);z.closeEntry();b.recycle();
   }types.append("</Types>");rels.append("</Relationships>");entry(z,"[Content_Types].xml",types.toString());entry(z,"_rels/.rels","<Relationships xmlns=\""+REL+"\">"+relation("rId1","officeDocument","ppt/presentation.xml")+"</Relationships>");entry(z,"ppt/_rels/presentation.xml.rels",rels.toString());entry(z,"ppt/presentation.xml","<p:presentation xmlns:p=\"http://schemas.openxmlformats.org/presentationml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><p:sldIdLst>"+list+"</p:sldIdLst><p:sldSz cx=\"9144000\" cy=\"6858000\"/><p:notesSz cx=\"6858000\" cy=\"9144000\"/></p:presentation>");
  }
 }
}
