package in.sahayak.documents;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import org.junit.*;import org.junit.runner.RunWith;import static org.junit.Assert.*;
import android.content.Context;import com.tom_roush.pdfbox.android.PDFBoxResourceLoader;
import com.tom_roush.pdfbox.pdmodel.*;import com.tom_roush.pdfbox.pdmodel.font.PDType1Font;import com.tom_roush.pdfbox.text.PDFTextStripper;import com.tom_roush.pdfbox.pdmodel.interactive.form.*;
import java.io.*;import java.util.*;import java.util.zip.*;

@RunWith(AndroidJUnit4.class)
public class PdfEngineTest {
 File source,dir;Context context;
 @Before public void setup()throws Exception{context=InstrumentationRegistry.getInstrumentation().getTargetContext();PDFBoxResourceLoader.init(context);dir=new File(context.getCacheDir(),"engine-tests");dir.mkdirs();source=new File(dir,"source.pdf");try(PDDocument d=new PDDocument()){for(int i=1;i<=3;i++){PDPage p=new PDPage();d.addPage(p);try(PDPageContentStream c=new PDPageContentStream(d,p)){c.beginText();c.setFont(PDType1Font.HELVETICA,18);c.newLineAtOffset(50,650);c.showText("Page "+i+" Suresh 5000");c.endText();}}d.save(source);}}
 File run(String action,String arg)throws Exception{File out=new File(dir,action+".result");PdfEngine.run(action,source,Collections.singletonList(source),out,arg,"");return out;}
 int count(File f)throws Exception{try(PDDocument d=PDDocument.load(f)){return d.getNumberOfPages();}}
 @Test public void mergeAndSplit()throws Exception{assertEquals(6,count(run("merge","")));try(ZipFile zip=new ZipFile(run("split",""))){assertEquals(3,zip.size());for(int i=1;i<=3;i++)try(PDDocument d=PDDocument.load(zip.getInputStream(zip.getEntry("page-"+i+".pdf")))){assertTrue(new PDFTextStripper().getText(d).contains("Page "+i));}}}
 @Test public void extractionAndOrder()throws Exception{File f=run("reorder","3,1");assertEquals(2,count(f));assertTrue(PdfEngine.text(f,"").startsWith("Page 3"));assertEquals(2,count(run("remove","2")));assertEquals(1,count(run("extract","2")));try{run("remove","1-3");fail("all-pages removal accepted");}catch(Exception expected){}}
 @Test public void rotateCropAndStamps()throws Exception{try(PDDocument d=PDDocument.load(run("rotate",""))){assertEquals(90,d.getPage(0).getRotation());}try(PDDocument d=PDDocument.load(run("crop","20"))){assertEquals(572,d.getPage(0).getCropBox().getWidth(),.1);}assertTrue(PdfEngine.text(run("watermark","DRAFT"),"").contains("DRAFT"));assertTrue(PdfEngine.text(run("numbers",""),"").contains("1 / 3"));assertTrue(PdfEngine.text(run("addtext","Hello"),"").contains("Hello"));assertTrue(PdfEngine.text(run("sign","Ramesh"),"").contains("Ramesh"));}
 @Test public void passwords()throws Exception{File protectedFile=run("protect","demoPass987");try{PDDocument.load(protectedFile);fail("PDF opened without password");}catch(com.tom_roush.pdfbox.pdmodel.encryption.InvalidPasswordException expected){}File unlocked=new File(dir,"unlocked.pdf");PdfEngine.run("unlock",protectedFile,Collections.emptyList(),unlocked,"","demoPass987");assertEquals(3,count(unlocked));}
 @Test public void imageAndCompression()throws Exception{File jpg=run("jpg","");try(ZipFile zip=new ZipFile(jpg)){assertEquals(3,zip.size());assertTrue(zip.getEntry("page-1.jpg").getSize()>1000);}assertEquals(3,count(run("compress","")));assertEquals(3,count(run("repair","")));}
 @Test public void exports()throws Exception{String text=PdfEngine.text(source,"");File word=new File(dir,"text.docx"),excel=new File(dir,"text.xlsx"),slides=new File(dir,"slides.pptx");PortableExports.word(text,word);PortableExports.excel(text,excel);PortableExports.slides(source,"",slides);try(ZipFile z=new ZipFile(word)){assertNotNull(z.getEntry("word/document.xml"));}try(ZipFile z=new ZipFile(excel)){assertNotNull(z.getEntry("xl/worksheets/sheet1.xml"));}try(ZipFile z=new ZipFile(slides)){assertNotNull(z.getEntry("ppt/slides/slide3.xml"));}assertTrue(PortableExports.compare("a","b").contains("A: a"));}
 @Test public void secureRasterRedaction()throws Exception{File out=new File(dir,"redacted.pdf");PortableExports.redact(source,"","1,0,0,100,100",out);assertEquals(3,count(out));assertFalse(PdfEngine.text(out,"").contains("Suresh"));try(PDDocument d=PDDocument.load(out)){android.graphics.Bitmap b=new com.tom_roush.pdfbox.rendering.PDFRenderer(d).renderImage(0,.2f);assertEquals(android.graphics.Color.BLACK,b.getPixel(b.getWidth()/2,b.getHeight()/2));b.recycle();}}
 @Test public void fieldsAndFlatten()throws Exception{try(PDDocument d=PDDocument.load(source)){PDAcroForm form=new PDAcroForm(d);d.getDocumentCatalog().setAcroForm(form);PDResources res=new PDResources();res.put(com.tom_roush.pdfbox.cos.COSName.getPDFName("Helv"),PDType1Font.HELVETICA);form.setDefaultResources(res);form.setDefaultAppearance("/Helv 12 Tf 0 g");PDTextField field=new PDTextField(form);field.setPartialName("person");form.getFields().add(field);field.getWidgets().get(0).setRectangle(new com.tom_roush.pdfbox.pdmodel.common.PDRectangle(50,500,200,30));field.getWidgets().get(0).setPage(d.getPage(0));d.getPage(0).getAnnotations().add(field.getWidgets().get(0));d.save(new File(dir,"form.pdf"));}File filled=new File(dir,"filled.pdf");PdfEngine.run("form",new File(dir,"form.pdf"),Collections.emptyList(),filled,"person=Ramesh","");assertTrue(PdfEngine.fields(filled,"").contains("Ramesh"));File flat=new File(dir,"flat.pdf");PdfEngine.run("flatten",filled,Collections.emptyList(),flat,"","");assertTrue(PdfEngine.text(flat,"").contains("Ramesh"));}
}
